language: bash

script:
  - echo "Timer started ‚è±Ô∏è"
  - for ((i=1; i<=3600; i+=1)); do
      echo "$i seconds completed";
      sleep 1;
    done
  - echo "üéâ 1 Hour completed successfully. Timer ended"
